obstacle_avoidance:
  obstacles:
  # Obs 1
    - loc: [1.2, 0.8, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [1.0, 0.3, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 2
    - loc: [2.5, 0.6, 0.0]
      rot: [0.0, 0.0, -0.43]
      scale: [1.2, 0.3, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 3
    - loc: [2.5, -0.6, 0.0]
      rot: [0.0, 0.0, -0.3]
      scale: [0.3, 0.3, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 4a
    - loc: [4.0, -2.0, 0.0]
      rot: [0.0, 0.0, 0.785]
      scale: [0.4, 0.4, 0.5]
      color: [1.0, 0.0, 0.0]
      type: cube
  # Obs 4b
    - loc: [3.0, -2.0, 0.0]
      rot: [0.0, 0.0, 0.785]
      scale: [0.4, 0.4, 0.5]
      color: [1.0, 0.0, 0.0]
      type: cube
  # Obs 5
    - loc: [5.0, -1.5, 0.0]
      rot: [0.0, 0.0, 0.52]
      scale: [1.6, 0.2, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 6
    - loc: [6.0, 0.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.3, 0.3, 0.5]
      color: [1.0, 0.0, 0.0]
      type: cube
  # Obs 7
    - loc: [7.7, 0.0, 0.0]
      rot: [0.0, 0.0, 0.785]
      scale: [0.3, 0.3, 0.5]
      color: [1.0, 0.0, 0.0]
      type: cube
  # Obs 8
    - loc: [5.0, 0.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.5, 0.5, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 9
    - loc: [2.8, 2.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.3, 2.0, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 10a
    - loc: [5.5, 4.0, 0.0]
      rot: [0.0, 0.0, 0.785]
      scale: [0.4, 0.4, 0.5]
      color: [0.0, 0.0, 1.0]
      type: cube
  # # Obs 10b
  #   - loc: [6.5, 4.2, 0.0]
  #     rot: [0.0, 0.0, 0.785]
  #     scale: [0.4, 0.4, 0.5]
  #     color: [0.0, 0.0, 1.0]
  #     type: cube
  # Obs 10c
    - loc: [7.5, 4.0, 0.0]
      rot: [0.0, 0.0, 1.04]
      scale: [0.4, 0.4, 0.5]
      color: [0.0, 0.0, 1.0]
      type: cube
  # Obs 11
    - loc: [6.5, 5.7, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [4.0, 0.2, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 12
    - loc: [10.2, 4.2, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.5, 0.5, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Obs 13a
    - loc: [10.0, 1.0, 0.0]
      rot: [0.0, 0.0, 0.785]
      scale: [0.14, 0.14, 0.5]
      color: [1.0, 1.0, 0.0]
      type: cube
  # Obs 13b
    - loc: [10.0, 0.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.2, 2.0, 0.5]
      color: [1.0, 1.0, 0.0]
      type: cube        
  # Obs 14
    - loc: [8.3, 0.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 5.0, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube  
  # Obs 15
    - loc: [11.6, 0.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 5.0, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube



# ========================================================================
  # Barrier:
  # Line 1: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [4.5, 2.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube  
    - loc: [4.5, 2.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube  
    - loc: [4.5, 2.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
    - loc: [4.5, 2.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
    - loc: [4.5, 3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
  # Line 2: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [4.75, 2.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube  
    - loc: [4.75, 2.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube  
    - loc: [4.75, 2.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
    - loc: [4.75, 2.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube
    - loc: [4.75, 3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 0.0]
      type: cube

  # Burdens Obstacles:
  # Line 1: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [1.0, -3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [1.0, -3.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [1.0, -3.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [1.0, -3.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [1.0, -4.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
  # Line 2: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [0.75, -3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.75, -3.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.75, -3.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.75, -3.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.75, -4.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
  # Line 3: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [0.5, -3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.5, -3.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.5, -3.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.5, -3.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.5, -4.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
  # Line 4: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [0.25, -3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.25, -3.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.25, -3.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.25, -3.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.25, -4.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
  # Line 5: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    - loc: [0.0, -3.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.0, -3.25, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube  
    - loc: [0.0, -3.5, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.0, -3.75, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
    - loc: [0.0, -4.0, 0.0]
      rot: [0.0, 0.0, 0.0]
      scale: [0.1, 0.1, 0.5]
      color: [0.0, 1.0, 1.0]
      type: cube
  
  
  # # Line 6: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #   - loc: [1.25, -3.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.25, -3.25, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.25, -3.5, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.25, -3.75, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.25, -4.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  # # Line 7: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #   - loc: [1.5, -3.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.5, -3.25, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.5, -3.5, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.5, -3.75, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.5, -4.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  # # Line 8: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #   - loc: [1.5, -3.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.5, -3.25, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.5, -3.5, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.5, -3.75, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.5, -4.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  # # Line 9: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #   - loc: [1.75, -3.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.75, -3.25, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [1.75, -3.5, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.75, -3.75, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [1.75, -4.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  # # Line 10: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #   - loc: [2.0, -3.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [2.0, -3.25, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube  
  #   - loc: [2.0, -3.5, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [2.0, -3.75, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  #   - loc: [2.0, -4.0, 0.0]
  #     rot: [0.0, 0.0, 0.0]
  #     scale: [0.1, 0.1, 0.5]
  #     color: [0.0, 1.0, 1.0]
  #     type: cube
  
