project:
  name: NLMPC_Mk2Gu

paths:
  quanser_python_dir: "../python"
  generated_trajectory_dir: "generated_qcar2_flatness_bezier_Mk1"
  generated_solver_dir: "generated_gurobi_nlmpc_solver"
  results_dir: "results"

trajectory:
  sample_time: 0.01
  psi_start: 0.0
  psi_end: 0.0
  start_speed: 0.0
  end_speed: 0.0
  waypoints: [
    [0.0, 0.0], 
    [3.0, 0.0],
    [6.0, 0.0], 
    [9.0, 0.0]
  ]

  segment_times: [3.0, 3.0, 3.0]

nlmpc:
  N: 13
  Ts: 0.07
  wheelbase: 0.25725

  constraints:
    vx_min: 0.0
    vx_max: 2.0
    delta_min: -0.5236
    delta_max: 0.5236
    ax_min: -1.0
    ax_max: 1.0

  weights:
    Q: [120.0, 120.0, 60.0, 80.0]
    R: [5.0, 100.0]
    P: [240.0, 240.0, 120.0, 160.0]

  solver:
    backend: gurobi
    output_flag: false
    save_template: true
    stop_on_failure: true
    max_consecutive_failures: 5

obstacle_avoidance:
  M: 100.0
  gamma: 0.25
  slack_weight: 100000000.0

tracking:
  vx_start: 0.3
  start_position_tolerance: 0.4
  start_yaw_tolerance: 0.15
  start_speed_tolerance: 0.03
  goal_position_tolerance: 0.05
  goal_yaw_tolerance: 0.1

qlabs:
  host: localhost

  qcar:
    actor_id: 5
    spawn:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.1
      scale: [0.1, 0.1, 0.1]

    steering_sign: -1.0
    speed_scale: 1.0

visualization:
  reference:
    stride: 10
    z: 0.015
    width: 0.025
    color: [1.0, 0.0, 0.0]

  waypoints:
    radius: 0.05
    stride: 24
    z: 0.025
    width: 0.015
    color: [0.0, 0.0, 0.3]
