project:
  name: OAMPC_Mk2c
paths:
  quanser_python_dir: ../python
  generated_trajectory_dir: generated_qcar2_flatness_bezier_Mk1
  results_dir: results

trajectory:
  sample_time: 0.02
  psi_start: 0.0
  psi_end: 3.14
  start_speed: 0.0
  end_speed: 0.0
  waypoints: [
     [0.0, 0.0],
     [1.0, 0.0],
     [2.0, 0.0],
     [2.5, -0.5],
     [3.0, -1.0],
     [3.6, -1.5],
     [4.5, -1.0],
     [5.5, -0.5],
     [6.0, 0.0],

     [6.0, 1.0],
     [5.0, 1.3],
     [4.0, 1.5],
     [3.5, 2.0],
     [3.5, 3.0],
     [4.0, 3.7],

     [5.0, 4.0],
     [6.0, 4.0],
     [7.5, 4.0],
     [9.0, 4.0],
     [9.5, 3.5],

     [10.0, 3.0],
     [10.0, 2.0],
     [10.0, 1.0],
     [10.0, 0.0],
     [10.0, -1.0],
     [10.0, -2.0],
     [9.5, -3.0],
     [9.0, -3.5],
     [8.0, -3.5]
  ]

  segment_times: [
    2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
    2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
    2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0
    ]

oampc:
  N: 30
  Ts: 0.02
  wheelbase: 0.25725
  epsilon: 0.001
  Q: [160.0, 160.0]
  R: [2.0, 2.0]
  constraints:
    vx_min: 0.0
    vx_max: 2.0
    delta_min: -0.5236
    delta_max: 0.5236
    ax_min: -1.0
    ax_max: 1.0
  solver:
    backend: gurobi
    output_flag: false
    stop_on_failure: true
    max_consecutive_failures: 5
    save_template: true

obstacle_avoidance:
  M: 100.0
  gamma: 0.35
  slack_weight: 100000000.0

  activation:
    radius: 2.0
    field_of_view: 180.0
    max_active_obstacles: 4
    deactive_distance: 0.25


tracking:
  goal_position_tolerance: 0.1


qlabs:
  host: localhost
  qcar:
    actor_id: 5
    spawn:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.1
      scale: [0.1, 0.1, 0.1]
    steering_sign: -1.0
    speed_scale: 1.0


visualization:
  reference:
    stride: 10
    z: 0.015
    width: 0.025
    color: [1.0, 0.0, 0.0]
  waypoints:
    radius: 0.05
    stride: 24
    z: 0.025
    width: 0.015
    color: [0.0, 0.0, 0.3]
